[package]
name = "example"
authors = ["BENM(Binxiao) FENG <binxiaofeng@gmail.com>"]
version = "0.1.0"

[dependencies]
env_logger = "0.4.0"
log = "0.3.7"
ordered-float = "0.3.0"
try_from = "0.2.0"
thrift = "0.13.0"
