[package]
name = "metadata"
version = "0.1.0"
authors = ["BENM FENG <binxiaofeng@gmail.com>"]
edition = "2018"

[dependencies]
capnp = "0.14.0"
capnp-rpc = "0.14.0"
futures = "0.3.0"
async-std = { version = "1.8.0", features = ["unstable"] }

[build-dependencies]
capnpc = "0.14.1"
